FitnessWebsite/urls.py
from django.contrib import admin
from django.urls import path
from user_auth.views import UserSignUpView, UserLoginView, UserLogoutView, FrontPageView, TrainerAddClientView
from notes.views import UserWorkoutsListView, DetailedWorkoutView, CreateWorkoutView, EditWorkoutView, DeleteWorkoutView, CreateWorkoutEntryView, EditWorkoutEntryView, DeleteWorkoutEntryView
from videos.views import VideoListView, VideoUploadView
from mails.views import SendMailView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', UserSignUpView, name="signup"),
    path('login/', UserLoginView, name="login"),
    path('logout/', UserLogoutView, name="logout"),
    path('', FrontPageView, name="frontpage"),
    path('addclient/', TrainerAddClientView, name="add_client"),
    path('<int:pk>/workouts', UserWorkoutsListView, name="workout_list"),
    path('<int:user_id>/workout/<int:workout_id>', DetailedWorkoutView, name="workout_detail"),
    path('<int:pk>/workouts/new', CreateWorkoutView, name="workout_create"),
    path('<int:user_id>/workout/<int:workout_id>/edit', EditWorkoutView, name="workout_edit"),
    path('<int:user_id>/workout/<int:workout_id>/delete', DeleteWorkoutView, name="workout_delete"),
    path('<int:user_id>/workout/<int:workout_id>/newentry', CreateWorkoutEntryView, name="workout_newentry"),
    path('<int:user_id>/workout/<int:workout_id>/<int:entry_id>/editentry', EditWorkoutEntryView, name="workout_editentry"),
    path('<int:user_id>/workout/<int:workout_id>/<int:entry_id>/deleteentry', DeleteWorkoutEntryView, name="workout_deleteentry"),
    path('videos/', VideoListView, name="video_list"),
    path('videos/upload', VideoUploadView, name="video_upload"),
    path('sendmail/', SendMailView, name="send_mail")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_auth/models.py
from django.db import models

# Create your models here.

user_auth/forms.py
from django import forms
from django.contrib.auth.models import User


class UserSignUpForm(forms.Form):
    username = forms.CharField(required=True, max_length=50)
    password = forms.CharField(required=True, widget=forms.PasswordInput())
    email = forms.EmailField(required=False)
    first_name = forms.CharField(required=False, max_length=50)
    last_name = forms.CharField(required=False, max_length=50)

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['password'],
            self.cleaned_data['email'],
            self.cleaned_data['first_name'],
            self.cleaned_data['last_name']
        )
        return user

class UserLoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=50)
    password = forms.CharField(required=True, widget=forms.PasswordInput())


class AddClientForm(forms.Form):
    user = forms.ModelChoiceField(required=True, queryset=User.objects.values())
    

user_auth/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User, Group, Permission
from .forms import UserSignUpForm, UserLoginForm, AddClientForm
from pathlib import Path
import os

# Create your views here.

def FrontPageView(request):
    has_perms = request.user.groups.filter(name='Staff').exists()
    return render(request, "frontpage.html", {'request': request, 'has_perms': has_perms})


def UserSignUpView(request):
    if request.method == 'POST':
        form = UserSignUpForm(request.POST)
        if form.is_valid():
            user_instance = User(
                username = request.POST.get('username'),
                password = make_password(request.POST.get('password')),
                email = request.POST.get('email'),
                first_name = request.POST.get('first_name'),
                last_name = request.POST.get('last_name')
            )
            user_instance.save()
            group = Group.objects.get_or_create(name="User")
            user_instance.groups.add(group[0])
            permission = Permission.objects.get(codename="view_videomodel")
            user_instance.user_permissions.add(permission)
            login(request, user_instance)
            return redirect("frontpage")
    else:
        if request.user.is_authenticated:
            return redirect("frontpage")
        form = UserSignUpForm()
    return render(request, "signup.html", {'form': form})


def UserLoginView(request): 

    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(username=request.POST.get('username'), password=request.POST.get('password'))
            if user is not None:
                login(request, user)
                return redirect(reverse_lazy('frontpage'))
            else:
                return redirect(reverse_lazy('login'))
    else:
        if request.user.is_authenticated:
            return redirect("frontpage")
        form = UserLoginForm()
    return render(request, "login.html", {'form': form})


def UserLogoutView(request):
    if request.method == "POST":
        logout(request)
        return redirect(reverse_lazy('frontpage'))
    return render(request, "logout.html")


def TrainerAddClientView(request):
    clients = [(client[0], client[4]) for client in list(User.objects.values_list())]
    if request.method == 'POST':
        form = AddClientForm(request.POST)
        if form.is_valid():
            group = Group.objects.get_or_create(name=f"{request.user.username}_clients")
            client = User.objects.get(id=request.POST.get('user'))
            client.groups.add(group[0])
            return redirect("frontpage")
    else:
        form = AddClientForm()
    return render(request, "add_client.html", {'form': form, 'clients': clients})

user_auth/templates/add_client.html
{% extends "master_template.html" %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
    <div class="greyborder d-flex flex-column mx-auto col-xl-4 px-2 pb-2 text-center">
        <div class="mt-1 text-center">
            <h1 class="display-4 mark">
                Add client
            </h1>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_user">Clients</label>
                <select required name="user" class="form-select" id="id_user">
                    {% for id,username in clients %}
                        <option value="{{ id }}">{{ username }}</option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-success my-2 white_text_button">Submit</button>
        </form>
        <div class="d-flex col-4 mx-auto">
            <a href="{% url 'frontpage' %}" class="mx-auto btn btn-info white_text_button my-2">Cancel</a>
        </div>
    </div>
{% endblock content %}

user_auth/templates/frontpage.html
{% extends "master_template.html" %}

{% block title %}
    Fitness Website
{% endblock title %}

{% block content %}
    <div class="greyborder d-flex flex-column mx-auto col-xl-6 px-1">
        <div class="mt-1 text-center">
            <h1 class="display-4 mark">Fitness App</h1>
        </div>
        {% if request.user.is_authenticated %}
            <div class="my-2 text-center mark">
                <span><strong>Welcome, {{ request.user.username }}</strong></span>
            </div>
            <div class="mb-2 d-flex">
                <a href="{% url 'workout_list' pk=request.user.id %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Workouts</a>
                <a href="{% url 'video_list' %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Videos</a>
                {% if has_perms %}
                    <a href="{% url 'add_client' %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Add client</a>
                {% endif %}
                <a href="{% url 'send_mail' %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Mail</a>
                <a href="{% url 'logout' %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Logout</a>
            </div>
        {% else %}
            <div class="my-2 text-center mark">
                <span><strong>Please log in or create an account to view more</strong></span>
            </div>
            <div class="mb-2 d-flex">
                <a href="{% url 'login' %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Login</a>
                <a href="{% url 'signup' %}" class="white_text_button bg-success p-2 mx-auto my-1 text-center rounded">Register</a>
            </div>
        {% endif %}
    </div>
{% endblock content %}

user_auth/templates/login.html
{% extends "master_template.html" %}

{% block title %}
    Login
{% endblock title %}

{% block content %}
    <div class="greyborder d-flex flex-column mx-auto col-xl-4 px-2 pb-2 text-center">
        <div class="mt-1 text-center">
            <h1 class="display-4 mark">
                Login
            </h1>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input required name="username" type="text" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input required name="password" type="password" class="form-control" id="password">
            </div>
            <button type="submit" class="btn btn-success my-2 white_text_button">Submit</button>
        </form>
        <div class="d-flex col-4 mx-auto">
            <a href="{% url 'frontpage' %}" class="mx-auto btn btn-info white_text_button">Cancel</a>
        </div>
    </div>
{% endblock content %}

user_auth/templates/logout.html
{% extends "master_template.html" %}

{% block title %}
    Logout
{% endblock title %}

{% block content %}
    <div class="greyborder d-flex flex-column mx-auto col-xl-6 px-1">
        <div class="mt-1 text-center mark">
            <h2><strong>Are you sure you want to log out</strong></h2>
        </div>
        <form method="POST">
            {% csrf_token %}
            <div class="d-flex">
                <button type="submit" class="btn btn-success my-2 white_text_button mx-auto">Yes, log me out</button>
            </div>
        </form>
        <div class="d-flex col-4 mx-auto">
            <a href="{% url 'frontpage' %}" class="mx-auto btn btn-info white_text_button mb-1">No, go back</a>
        </div>
    </div>
{% endblock content %}

user_auth/templates/master_template.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- bootstrap link -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <!-- css link -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'style.css' %}">
    </head>
    <body>
        <div class="container my-4">
            {% block content %}
            {% endblock %}
        </div>
        <!-- bootstrap script -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>

user_auth/templates/signup.html
{% extends "master_template.html" %}

{% block title %}
    Sign up
{% endblock title %}

{% block content %}
    <div class="greyborder d-flex flex-column mx-auto col-xl-4 px-2 pb-2 text-center">
        <div class="mt-1 text-center">
            <h1 class="display-4 mark">
                Create an account
            </h1>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input required name="username" type="text" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input required name="password" type="password" class="form-control" id="password">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input name="email" type="email" class="form-control" id="email">
            </div>
            <div class="form-group">
                <label for="first_name">First name</label>
                <input name="first_name" type="text" class="form-control" id="first_name">
            </div>
            <div class="form-group">
                <label for="last_name">Last name</label>
                <input name="last_name" type="text" class="form-control" id="last_name">
            </div>
            <button type="submit" class="btn btn-success my-2 white_text_button">Submit</button>
        </form>
        <div class="d-flex col-4 mx-auto">
            <a href="{% url 'frontpage' %}" class="mx-auto btn btn-info white_text_button">Cancel</a>
        </div>
{% endblock content %}